### ISSUE TITLE
discrepancies between progress bar and actual cooldown

### ISSUE THREAD

**Issue by tinbtb** [priprii/GenshinOverlay#4]
Cooldown progress bar lags behind the actual cooldown and this lag depends on a skill cooldown duration, i.e. for barbara's skill the cooldown is 27s and lag is ~3s, but for Chongyun's 15s the lag is ~2s and for shorter cooldown lag is negligible. With difference this big it's not possible to fix it with the "Offset".

When lag is more than "Override" it's possible to cast a skill again without triggering the progress bar update.

**Comment by priprii** [comment]
There shouldn't be any difference between the delay, so that's weird if there is. It isn't different for me personally with using default config.

Is this happening all the time or only every now and then? What time of day are you testing with? As bright backgrounds can cause delay to the OCR processing, but shouldn't cause delay to the cooldown.

For situations where you can use a skill before the bar is finished, you can press E again after the bar is finished which should then cause the bar to be on cooldown again. But I would suggest setting the offset so that the bar finishes in advance and just assume that the skill might still be on cooldown for a little bit.

I may add an option to have the OCR engine always checking cooldown at an interval so that it can make corrections if necessary.

**Comment by tinbtb** [comment]
Happens all the time, debug shows confidence >0.9. Checked with the stopwatch, difference between Barbara's and Xiangling's lags is more than a second, definitely related to the skill cooldown duration.

**Comment by priprii** [comment]
v1.4 may fix this issue, please confirm if the changes are adequate.

**Comment by tinbtb** [comment]
There is still a little difference in lags for very long (Barbara's) and very short (Keqing's) skills, but I got used to this and with offset of -0.9 it doesn't bother me anymore.
