### ISSUE TITLE
Detection is slow

### ISSUE THREAD

**Issue by bluesfear** [priprii/GenshinOverlay#7]
If you switch quickly after using elemental skill on a character, the overlay doesnt detect the skill going on cooldown, i think its reading the screen too slow?

Cause the second I press E on a character I spam the number key to swtich characters, and 100% of the time its not picking up the skill going on CD, but if i wait like 1 sec, then it does work.

**Comment by priprii** [comment]
This should only happen if your CPU can't process it fast enough or if the OCR engine is having trouble returning a result past the confidence threshold.

The minimum delay between the OCR engine doing a capture from when you press the E key is 100ms. This is to account for some characters having an intitial cooldown time delay (this happens for characters like Fischl and Xiangling, but not characters like Barbara, not sure why). Regardless, the game doesn't even let you switch character after casting skill for around 250ms, so the OCR engine can make around 3 attempts before you being able to switch character.

The OCR processing itself only takes around 4ms on an i7 CPU, there's just a static delay of 100ms between attempts to reduce CPU load but I may add this as a modifiable value.

If the OCR engine can't return a quality value before you switch character, it will ignore it and the skill won't go on cooldown.

Low confidence results are either due to the cooldown text rectangle not being set correctly or very bright background behind the cooldown text (so around noon time in-game is when this would be a most prominent issue).

You can try the debug option to check whether the OCR engine is having issues.

**Comment by priprii** [comment]
v1.4 may fix this issue.

**Comment by bluesfear** [comment]
I dont have the newest CPU. I am running i5-4600k. Thanks for the detail explanation. Love your work

**Comment by bluesfear** [comment]
Works like a chime in v1.4. Thank you for the update
